api_login_check:
    path: /api/login_check

controllers:
    resource:  # Resource definition for other controllers
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
